/*
HPC Portal - API

An interface for working with HPC clusters.

API version: 1.9.10-9
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OnboardUser type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OnboardUser{}

// OnboardUser struct for OnboardUser
type OnboardUser struct {
	Namespace string `json:"namespace"`
	Cluster string `json:"cluster"`
}

type _OnboardUser OnboardUser

// NewOnboardUser instantiates a new OnboardUser object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOnboardUser(namespace string, cluster string) *OnboardUser {
	this := OnboardUser{}
	this.Namespace = namespace
	this.Cluster = cluster
	return &this
}

// NewOnboardUserWithDefaults instantiates a new OnboardUser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOnboardUserWithDefaults() *OnboardUser {
	this := OnboardUser{}
	return &this
}

// GetNamespace returns the Namespace field value
func (o *OnboardUser) GetNamespace() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value
// and a boolean to check if the value has been set.
func (o *OnboardUser) GetNamespaceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Namespace, true
}

// SetNamespace sets field value
func (o *OnboardUser) SetNamespace(v string) {
	o.Namespace = v
}

// GetCluster returns the Cluster field value
func (o *OnboardUser) GetCluster() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Cluster
}

// GetClusterOk returns a tuple with the Cluster field value
// and a boolean to check if the value has been set.
func (o *OnboardUser) GetClusterOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cluster, true
}

// SetCluster sets field value
func (o *OnboardUser) SetCluster(v string) {
	o.Cluster = v
}

func (o OnboardUser) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OnboardUser) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["namespace"] = o.Namespace
	toSerialize["cluster"] = o.Cluster
	return toSerialize, nil
}

func (o *OnboardUser) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"namespace",
		"cluster",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOnboardUser := _OnboardUser{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOnboardUser)

	if err != nil {
		return err
	}

	*o = OnboardUser(varOnboardUser)

	return err
}

type NullableOnboardUser struct {
	value *OnboardUser
	isSet bool
}

func (v NullableOnboardUser) Get() *OnboardUser {
	return v.value
}

func (v *NullableOnboardUser) Set(val *OnboardUser) {
	v.value = val
	v.isSet = true
}

func (v NullableOnboardUser) IsSet() bool {
	return v.isSet
}

func (v *NullableOnboardUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOnboardUser(val *OnboardUser) *NullableOnboardUser {
	return &NullableOnboardUser{value: val, isSet: true}
}

func (v NullableOnboardUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOnboardUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


