/*
HPC Portal - API

An interface for working with HPC clusters.

API version: 1.9.10-9
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Container type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Container{}

// Container struct for Container
type Container struct {
	Name string `json:"name"`
	TerminationState NullableContainerTerminationState `json:"termination_state,omitempty"`
}

type _Container Container

// NewContainer instantiates a new Container object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContainer(name string) *Container {
	this := Container{}
	this.Name = name
	return &this
}

// NewContainerWithDefaults instantiates a new Container object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContainerWithDefaults() *Container {
	this := Container{}
	return &this
}

// GetName returns the Name field value
func (o *Container) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Container) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Container) SetName(v string) {
	o.Name = v
}

// GetTerminationState returns the TerminationState field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Container) GetTerminationState() ContainerTerminationState {
	if o == nil || IsNil(o.TerminationState.Get()) {
		var ret ContainerTerminationState
		return ret
	}
	return *o.TerminationState.Get()
}

// GetTerminationStateOk returns a tuple with the TerminationState field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Container) GetTerminationStateOk() (*ContainerTerminationState, bool) {
	if o == nil {
		return nil, false
	}
	return o.TerminationState.Get(), o.TerminationState.IsSet()
}

// HasTerminationState returns a boolean if a field has been set.
func (o *Container) HasTerminationState() bool {
	if o != nil && o.TerminationState.IsSet() {
		return true
	}

	return false
}

// SetTerminationState gets a reference to the given NullableContainerTerminationState and assigns it to the TerminationState field.
func (o *Container) SetTerminationState(v ContainerTerminationState) {
	o.TerminationState.Set(&v)
}
// SetTerminationStateNil sets the value for TerminationState to be an explicit nil
func (o *Container) SetTerminationStateNil() {
	o.TerminationState.Set(nil)
}

// UnsetTerminationState ensures that no value is present for TerminationState, not even an explicit nil
func (o *Container) UnsetTerminationState() {
	o.TerminationState.Unset()
}

func (o Container) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Container) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if o.TerminationState.IsSet() {
		toSerialize["termination_state"] = o.TerminationState.Get()
	}
	return toSerialize, nil
}

func (o *Container) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varContainer := _Container{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varContainer)

	if err != nil {
		return err
	}

	*o = Container(varContainer)

	return err
}

type NullableContainer struct {
	value *Container
	isSet bool
}

func (v NullableContainer) Get() *Container {
	return v.value
}

func (v *NullableContainer) Set(val *Container) {
	v.value = val
	v.isSet = true
}

func (v NullableContainer) IsSet() bool {
	return v.isSet
}

func (v *NullableContainer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContainer(val *Container) *NullableContainer {
	return &NullableContainer{value: val, isSet: true}
}

func (v NullableContainer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContainer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


