/*
HPC Portal - API

An interface for working with HPC clusters.

API version: 1.9.10-9
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the JobDescriptionResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobDescriptionResp{}

// JobDescriptionResp struct for JobDescriptionResp
type JobDescriptionResp struct {
	Detail string `json:"detail"`
}

type _JobDescriptionResp JobDescriptionResp

// NewJobDescriptionResp instantiates a new JobDescriptionResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobDescriptionResp(detail string) *JobDescriptionResp {
	this := JobDescriptionResp{}
	this.Detail = detail
	return &this
}

// NewJobDescriptionRespWithDefaults instantiates a new JobDescriptionResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobDescriptionRespWithDefaults() *JobDescriptionResp {
	this := JobDescriptionResp{}
	return &this
}

// GetDetail returns the Detail field value
func (o *JobDescriptionResp) GetDetail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Detail
}

// GetDetailOk returns a tuple with the Detail field value
// and a boolean to check if the value has been set.
func (o *JobDescriptionResp) GetDetailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Detail, true
}

// SetDetail sets field value
func (o *JobDescriptionResp) SetDetail(v string) {
	o.Detail = v
}

func (o JobDescriptionResp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobDescriptionResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["detail"] = o.Detail
	return toSerialize, nil
}

func (o *JobDescriptionResp) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"detail",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJobDescriptionResp := _JobDescriptionResp{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJobDescriptionResp)

	if err != nil {
		return err
	}

	*o = JobDescriptionResp(varJobDescriptionResp)

	return err
}

type NullableJobDescriptionResp struct {
	value *JobDescriptionResp
	isSet bool
}

func (v NullableJobDescriptionResp) Get() *JobDescriptionResp {
	return v.value
}

func (v *NullableJobDescriptionResp) Set(val *JobDescriptionResp) {
	v.value = val
	v.isSet = true
}

func (v NullableJobDescriptionResp) IsSet() bool {
	return v.isSet
}

func (v *NullableJobDescriptionResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobDescriptionResp(val *JobDescriptionResp) *NullableJobDescriptionResp {
	return &NullableJobDescriptionResp{value: val, isSet: true}
}

func (v NullableJobDescriptionResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobDescriptionResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


