/*
HPC Portal - API

An interface for working with HPC clusters.

API version: 1.9.10-9
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TargetStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TargetStatus{}

// TargetStatus struct for TargetStatus
type TargetStatus struct {
	Url string `json:"url"`
}

type _TargetStatus TargetStatus

// NewTargetStatus instantiates a new TargetStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTargetStatus(url string) *TargetStatus {
	this := TargetStatus{}
	this.Url = url
	return &this
}

// NewTargetStatusWithDefaults instantiates a new TargetStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTargetStatusWithDefaults() *TargetStatus {
	this := TargetStatus{}
	return &this
}

// GetUrl returns the Url field value
func (o *TargetStatus) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *TargetStatus) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *TargetStatus) SetUrl(v string) {
	o.Url = v
}

func (o TargetStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TargetStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *TargetStatus) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTargetStatus := _TargetStatus{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTargetStatus)

	if err != nil {
		return err
	}

	*o = TargetStatus(varTargetStatus)

	return err
}

type NullableTargetStatus struct {
	value *TargetStatus
	isSet bool
}

func (v NullableTargetStatus) Get() *TargetStatus {
	return v.value
}

func (v *NullableTargetStatus) Set(val *TargetStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableTargetStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableTargetStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTargetStatus(val *TargetStatus) *NullableTargetStatus {
	return &NullableTargetStatus{value: val, isSet: true}
}

func (v NullableTargetStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTargetStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


