/*
HPC Portal - API

An interface for working with HPC clusters.

API version: 1.9.10-9
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the JobDescription type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobDescription{}

// JobDescription struct for JobDescription
type JobDescription struct {
	Description string `json:"description"`
}

type _JobDescription JobDescription

// NewJobDescription instantiates a new JobDescription object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobDescription(description string) *JobDescription {
	this := JobDescription{}
	this.Description = description
	return &this
}

// NewJobDescriptionWithDefaults instantiates a new JobDescription object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobDescriptionWithDefaults() *JobDescription {
	this := JobDescription{}
	return &this
}

// GetDescription returns the Description field value
func (o *JobDescription) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *JobDescription) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *JobDescription) SetDescription(v string) {
	o.Description = v
}

func (o JobDescription) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobDescription) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["description"] = o.Description
	return toSerialize, nil
}

func (o *JobDescription) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"description",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJobDescription := _JobDescription{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJobDescription)

	if err != nil {
		return err
	}

	*o = JobDescription(varJobDescription)

	return err
}

type NullableJobDescription struct {
	value *JobDescription
	isSet bool
}

func (v NullableJobDescription) Get() *JobDescription {
	return v.value
}

func (v *NullableJobDescription) Set(val *JobDescription) {
	v.value = val
	v.isSet = true
}

func (v NullableJobDescription) IsSet() bool {
	return v.isSet
}

func (v *NullableJobDescription) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobDescription(val *JobDescription) *NullableJobDescription {
	return &NullableJobDescription{value: val, isSet: true}
}

func (v NullableJobDescription) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobDescription) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


