/*
HPC Portal - API

An interface for working with HPC clusters.

API version: 1.9.10-9
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PVCViewer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PVCViewer{}

// PVCViewer struct for PVCViewer
type PVCViewer struct {
	Url string `json:"url"`
	Status Status `json:"status"`
}

type _PVCViewer PVCViewer

// NewPVCViewer instantiates a new PVCViewer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPVCViewer(url string, status Status) *PVCViewer {
	this := PVCViewer{}
	this.Url = url
	this.Status = status
	return &this
}

// NewPVCViewerWithDefaults instantiates a new PVCViewer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPVCViewerWithDefaults() *PVCViewer {
	this := PVCViewer{}
	return &this
}

// GetUrl returns the Url field value
func (o *PVCViewer) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *PVCViewer) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *PVCViewer) SetUrl(v string) {
	o.Url = v
}

// GetStatus returns the Status field value
func (o *PVCViewer) GetStatus() Status {
	if o == nil {
		var ret Status
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *PVCViewer) GetStatusOk() (*Status, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *PVCViewer) SetStatus(v Status) {
	o.Status = v
}

func (o PVCViewer) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PVCViewer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *PVCViewer) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPVCViewer := _PVCViewer{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPVCViewer)

	if err != nil {
		return err
	}

	*o = PVCViewer(varPVCViewer)

	return err
}

type NullablePVCViewer struct {
	value *PVCViewer
	isSet bool
}

func (v NullablePVCViewer) Get() *PVCViewer {
	return v.value
}

func (v *NullablePVCViewer) Set(val *PVCViewer) {
	v.value = val
	v.isSet = true
}

func (v NullablePVCViewer) IsSet() bool {
	return v.isSet
}

func (v *NullablePVCViewer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePVCViewer(val *PVCViewer) *NullablePVCViewer {
	return &NullablePVCViewer{value: val, isSet: true}
}

func (v NullablePVCViewer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePVCViewer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


