/*
HPC Portal - API

An interface for working with HPC clusters.

API version: 1.9.10-9
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PVCItemBasic type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PVCItemBasic{}

// PVCItemBasic struct for PVCItemBasic
type PVCItemBasic struct {
	Name string `json:"name"`
	Owner string `json:"owner"`
}

type _PVCItemBasic PVCItemBasic

// NewPVCItemBasic instantiates a new PVCItemBasic object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPVCItemBasic(name string, owner string) *PVCItemBasic {
	this := PVCItemBasic{}
	this.Name = name
	this.Owner = owner
	return &this
}

// NewPVCItemBasicWithDefaults instantiates a new PVCItemBasic object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPVCItemBasicWithDefaults() *PVCItemBasic {
	this := PVCItemBasic{}
	return &this
}

// GetName returns the Name field value
func (o *PVCItemBasic) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PVCItemBasic) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PVCItemBasic) SetName(v string) {
	o.Name = v
}

// GetOwner returns the Owner field value
func (o *PVCItemBasic) GetOwner() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value
// and a boolean to check if the value has been set.
func (o *PVCItemBasic) GetOwnerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Owner, true
}

// SetOwner sets field value
func (o *PVCItemBasic) SetOwner(v string) {
	o.Owner = v
}

func (o PVCItemBasic) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PVCItemBasic) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["owner"] = o.Owner
	return toSerialize, nil
}

func (o *PVCItemBasic) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"owner",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPVCItemBasic := _PVCItemBasic{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPVCItemBasic)

	if err != nil {
		return err
	}

	*o = PVCItemBasic(varPVCItemBasic)

	return err
}

type NullablePVCItemBasic struct {
	value *PVCItemBasic
	isSet bool
}

func (v NullablePVCItemBasic) Get() *PVCItemBasic {
	return v.value
}

func (v *NullablePVCItemBasic) Set(val *PVCItemBasic) {
	v.value = val
	v.isSet = true
}

func (v NullablePVCItemBasic) IsSet() bool {
	return v.isSet
}

func (v *NullablePVCItemBasic) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePVCItemBasic(val *PVCItemBasic) *NullablePVCItemBasic {
	return &NullablePVCItemBasic{value: val, isSet: true}
}

func (v NullablePVCItemBasic) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePVCItemBasic) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


